### PR TITLE
Test case decide_from_context_df with month

### PR DESCRIPTION
**Pull request by PaulineMCraft**
Reproduction case for #152

### CODE REVIEW

**Comment by PaulineMCraft** [comment]
Testing DataFrame : 
                                               month     scream    goat
2015-07-01 00:00:00+00:00      7  33.139700 -999999
2015-08-01 00:00:00+00:00      8  33.336792 -999999
2015-09-01 00:00:00+00:00      9  51.332880 -999999
2015-10-01 00:00:00+00:00     10  27.245916 -999999
2015-11-01 00:00:00+00:00     11  38.785276 -999999

**Comment by sperretcraft** [comment]
The #158 makes the tests pass. It is a good idea to keep them to prevent any regression in future work.

**Comment by rmdh** [comment]
Is this a test that failed before the fixing PR?
May be better to add some decision rules in the tested tree where the month appears, to also check that the interpretation works correctly on this type?

**Comment by Totoketchup** [comment]
@sperretcraft So it's not a bug as Pauline reported?

**Comment by sperretcraft** [comment]
Not anymore thanks to the PR #158 which change the way `pandas` handle rows with different types in it.

**Pull request merged**
