### PR TITLE
Feature/jupyter tree visualization

### PR DESCRIPTION
**Pull request by Totoketchup**

### CODE REVIEW

**Comment by cibeah** [comment]
Really cool !

What works : 
Full tree displaying just as in the interpreter when I save the html_tree returned by the display_tree function in a html file. (on Chrome 70 & Firefox 63) Also makes browsing the tree much faster than in the interpreter. 
Changing the height from 500 to 900 makes for a better experience (but maybe it's just personal taste). 

What does not work : 
Can't manage to display the tree directly in the notebook, photo :
2018-11-08_16h08_05
Maybe there is some more steps to do to set up the notebook ? 

Executing the script directly in command line does return  a display object : 
2018-11-08_16h17_54

**Comment by cibeah** [comment]
Upgrading to Jupyter 0.35.3 solves everything ! 

2018-11-08_16h46_19

**Comment by Totoketchup** [comment]
@cibeah  you can now set the height in the function 👌

**Comment by cibeah** [comment]
Great, thank you !

**Pull request merged**
